### PR TITLE
Base file imports

### PR DESCRIPTION
**Pull request by shawntanzk**
Switch to base file imports

### CODE REVIEW

**Comment by shawntanzk** [comment]
Current issue seems to be `Cause: /work/src/ontology/imports/merged_import.owl (No such file or directory)` 
This error occurs when i try to run `sh run.sh make imports/merged_import.owl` or `sh run.sh make no-mirror-refresh-imports` not too sure how to fix given that it almost seems cyclical

**Comment by shawntanzk** [comment]
Issue seems to be merge is trying to bring in edit file and edit file is trying to bring in merge - removed merge import from edit file and ran `sh run.sh make imports/merged_import.owl` and worked - now running `sh run.sh make no-mirror-refresh-imports` and will check that everything is in place

**Comment by shawntanzk** [comment]
Currently HEAPS of CHEBI and CARO dangling classes - I think this is the downside to base file imports.
We can fix it by importing them in, or deleting the axioms.
Downside to importing: 
they will probably bring in even more dangling classes
Downside to deleting:
if we programmatically do it, it might result in future users not being able to use that import if they don't know we did that
Happy to do either.

**Comment by shawntanzk** [comment]
Of note: other ontologies remove it

**Comment by matentzn** [comment]
Best import Chebi. You can potentially delete CARO, but try to import it.. just to see wether you run into consistency issues..

**Comment by shawntanzk** [comment]
Note to self:
there are a couple of NBO terms to deal with too.
Will try to fix them in this PR too: https://github.com/obophenotype/provisional_cell_ontology/pull/24

**Comment by shawntanzk** [comment]
dangling classes still present

**Comment by shawntanzk** [comment]
after refreshing chebi mirror (in case it was an error from before) and rerunning `sh run.sh make no-mirror-refresh-imports` dangling classes still present. Not sure if I need to make a release to fix it? will try.

**Comment by matentzn** [comment]
Ask me in slack.. You dont need a release.

**Comment by shawntanzk** [comment]
2 things left to fix:

- [ ] Remove NCBITaxon_Union_*
- [ ] Add SO import for SO_0000704 (holds all the ncbigene and ensembl)

**Comment by shawntanzk** [comment]
after alot of stupid mistakes my me, and heaps of help from @matentzn, branch is finally clean.
Just before I merge just wanted to make sure @dosumis is alright with the stuff I exclude:

```
  exclude_iri_patterns:
    - <http://www.informatics.jax.org/marker/MGI:*>
    - <http://purl.obolibrary.org/obo/OBA_*>
    - <http://purl.obolibrary.org/obo/ENVO_*>
    - <http://purl.obolibrary.org/obo/OBI_*>
    - <http://purl.obolibrary.org/obo/GOCHE_*>
    - <http://purl.obolibrary.org/obo/CARO_*>
    - <http://purl.obolibrary.org/obo/NCBITaxon_Union_*>
    - <http://www.genenames.org/cgi-bin/gene_symbol_report*>
```

If so, could you help give a thumbs up please?

**Review by matentzn — APPROVED** [review]
Wow @shawntanzk major effort. This looks great! Aside from the pruned ID spaces (which need the nod from @dosumis), I think this is all awesome!

**Pull request merged**
